
description = "Update the Neo4j knowledge graph with structured learning data."
prompt = '''
**Input**: `{{args}}` - A JSON string containing the analyzed data from a lesson.

## Update Process

1.  **Parse Input**:
    -   Parse the input JSON string to extract information: `lesson_name`, `key_concepts`, etc.

2.  **Attempt Update with Duplication Check**:
    -   First, **try to use** the `read_neo4j_cypher` tool to check if a `Lesson` node with the same `lesson_name` already exists.
        -   **Query Example**: `MATCH (lesson:Lesson {name: $lesson_name}) RETURN lesson`
    -   **If the query succeeds and returns a result**: Stop the process and report that this lesson has already been updated.
    -   **If the query succeeds and returns no results**: Proceed to generate and execute the update queries using `write_neo4j_cypher`. After execution, verify the update and report success.

3.  **Fallback on Tool Failure**:
    -   **If any Neo4j tool call fails** (e.g., `read_neo4j_cypher` or `write_neo4j_cypher` are not available):
        a.  Clearly state that the automatic memory update failed because the required tools are not in your environment.
        b.  **Do not stop.** Instead, generate the complete set of Cypher queries that *would* have been executed.
        c.  Present these queries to the user in a formatted code block as the final output.

## Example Input JSON
```json
{
  "lesson_name": "L15_Debugging_Functions",
  "key_concepts": [
    "Debugging: The process of finding and fixing errors in source code."
  ],
  "implementation_patterns": [
    "Print debugging: Using print statements to inspect variable states."
  ],
  "concept_connections": [
    "Connects to testing principles."
  ],
  "main_learning_insight": "A systematic approach to debugging is more effective than random guessing.",
  "skill_progression": "Moved from ad-hoc debugging to a structured process."
}
```

<!-- TODO(human): Review the entire document for any other references to Boot_Dev_Course observations
     that should be updated to match the new Lesson node duplication check approach.
     Also consider if any additional examples or clarifications would be helpful. -->
'''
